//Author: Seth/Sheriff John Brown
//DnD dice roller/simulator
import java.util.Scanner;
import java.util.InputMismatchException;

public class Main {
    final static int min = 1;
    private static int max;
    static int getMax() {
        return max; }
    static void setMax(int newmax) {
        max = newmax;
    }
    private static int random;
    static int getRandom() {
        return random;
    }
    static void setRandom(int newrandom) {
        random = newrandom;
    }
    //Getters and Setters are not necessary for the program to work
    //I felt it was better to practice doing things the right way rather than just a way that works
    public static void main(String[] args) {
        System.out.println("Let's Roll!, Your Fate is now in Jah's Hands");
        System.out.println("""      
       .-------.   `______'
      /   o   /|  `/\\     \\'
     /_______/o| `/o \\  o  \\'
     | o     | |`/   o\\_____\\'
     |   o   |o/`\\o   /o    /
     |     o |/  `\\ o/  o  /
     '-------'    `\\/____o/
                """);
        input();
    }
    public static void input() {
        try {
            Scanner input = new Scanner(System.in);
            System.out.print("D:");
            setMax(Math.abs(input.nextInt()));
            //sets variable max to the absolute value of the user input(ABS used in case input is negative)
            reRoll();
        }
        catch(InputMismatchException ex) {
            System.out.println("That's Universally Stupid Man, type a whole number");
            input();
            //If user inputs a bad value lets them try again
        }
    }
    public static void reRoll() {
        try {
            System.out.println("Type 1 to roll, Type 2 to reset dice, Type 3 to roll the dice multiple times in a row, Type anything to exit");
            Scanner input1 = new Scanner(System.in);
            int newinput = input1.nextInt();
            switch(newinput) {
                case 1:
                    randomNumber();
                    reRoll();
                    break;
                case 2:
                    input();
                    break;
                case 3:
                    try {
                        System.out.print("\nPlease type the number of times you would like to roll the dice:");
                        int y = Math.abs(input1.nextInt());
                        //sets variable y to the absolute value of the user input(ABS used in case input is negative)
                        int totalNumber = 0;
                        for (int x = 0; x<y; x++) {
                            randomNumber();
                            System.out.println();
                            totalNumber += getRandom();
                        }
                        //Will roll the dice(RandomNumber() method) the number of times(y) the user inputted
                        //Will add the number generated by RandomNumber() to totalNumber used later to find the total number of all the dice and average
                        System.out.println("The total number is:"+totalNumber);
                        printNumbers(totalNumber);
                        System.out.println("\nThe average is:"+totalNumber/y);
                        printNumbers((totalNumber/y));
                        //total number/number of times rolled to find average
                        reRoll();
                    }
                    catch(InputMismatchException ex) {
                        System.out.println("That's Universally Stupid Man, type a whole number");
                        reRoll();
                        //If user inputs a bad value lets them try again
                    }
                    break;
                default:System.out.println("Until we meet again!");
                //if none of the above cases are true the program will end
            }
        }
        catch(InputMismatchException ex) {
        System.out.println("Until we meet again!");
            //if user does not input a whole number program will end
        }
    }
    public static void printNumbers(int number) {
        //Prints numbers in ASCII art line by line
        //Each array stores the block of ascii art line by line
        String[] art0 = {" 0000 ","00  00","00  00","00  00"," 0000 "};
        String[] art1 = {"1111  ","  11  ","  11  ","  11  ","111111"};
        String[] art2 = {" 2222 ","22  22","   22 ","  22  ","222222"};
        String[] art3 = {" 3333 ","33  33","   333","33  33"," 3333 "};
        String[] art4 = {"44  44","44  44","444444","    44","    44"};
        String[] art5 = {"555555","55    ","55555 ","    55","55555 "};
        String[] art6 = {" 6666 ","66    ","66666 ","66  66"," 6666 "};
        String[] art7 = {"777777","   77 ","  77  "," 77   ","77    "};
        String[] art8 = {" 8888 ","88  88"," 8888 ","88  88"," 8888 "};
        String[] art9 = {"999999","99  99","999999","    99","   99 ","  99  "};
        String[][] arrays = {art0,art1,art2,art3,art4,art5,art6,art7,art8,art9};
        //Creates an array of the array to choose the correct number for each digit
        if (number<10) {
            for (int x = 0; x < 5; x++) {
                System.out.print(arrays[number][x]);
                System.out.print("\n");
            }
            //takes the number and chooses the correct array based on the number
            //Then takes that array choosen and prints each element of the array in a new line
        }
        else if (number<100) {
            for (int x = 0; x < 5; x++) {
                System.out.print(arrays[number/10][x]);
                //takes the first digit and chooses the correct array
                //prints a line of that array based on the first digit
                System.out.print("    ");
                //creates a space between the two numbers
                System.out.print(arrays[number%10][x]);
                //takes the second digit and chooses the correct array
                //prints a line of that array based on the second digit
                System.out.print("\n");
            }
        }
        else if (number<1000) {
            for (int x =0; x<5; x++) {
                System.out.print(arrays[number/100][x]);
                //takes the first digit and chooses the correct array
                //prints a line of that array based on the first digit
                System.out.print("    ");
                //creates a space between the numbers
                System.out.print(arrays[(number%100)/10][x]);
                //takes the second digit and chooses the correct array
                //prints a line of that array based on the second digit
                System.out.print("    ");
                //creates a space between the numbers
                System.out.print(arrays[number%10][x]);
                //takes the third digit and chooses the correct array
                //prints a line of that array based on the third digit
                System.out.print("\n");
            }
        }
        //These loops will print the ASCII art out line by line
        //this is necessary to print two blocks of text side by side otherwise they will print below eachother
        //The loops choose the correct number then will print the first line of each with a space between them
        //It will repeat this printing of each line side by side 5 times
        else {
            System.out.println(number);
            //if above 4 digit or more will just print out the number
        }
    }
    public static void randomNumber(){
        setRandom((int) (Math.random() * (getMax() - Main.min + 1) + Main.min));
        //sets a random number between the max set by the user and the minimum(both are inclusive)
        printNumbers(getRandom());
    }
}
